### ISSUE TITLE
Different values for battery resistor depending on board selection

### ISSUE THREAD

**Issue by unlogisch04** [SlimeVR/SlimeVR-Firmware-WebBuilder#12]
The default values for battery resistors should change for each board.
Also the default pins (not sure if they do already)
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/commit/3337d5a5392324d662398a5943636e160a102c38

**Comment by loucass003** [comment]
@unlogisch04 would you be able to make me a list of all the resistor values based on the boards?

```ts
const batteryResistor = {
        [BoardType.BOARD_SLIMEVR]:  X,
        [BoardType.BOARD_SLIMEVR_DEV]:  X,
        [BoardType.BOARD_NODEMCU]:  X,
        [BoardType.BOARD_WEMOSD1MINI]:  X,
        [BoardType.BOARD_ESP01]:  X,
        [BoardType.BOARD_TTGO_TBASE]: X,
        [BoardType.BOARD_WROOM32]: X,
};
 ```

**Comment by unlogisch04** [comment]
See discord discussion https://discord.com/channels/817184208525983775/1061474253490376744/1136014237035139122
