### ISSUE TITLE
IMU Rotation is 180° wrong compared to the one in the firmware

### ISSUE THREAD

**Issue by unlogisch04** [SlimeVR/SlimeVR-Firmware-WebBuilder#4]
Input line https://github.com/SlimeVR/SlimeVR-Firmware-WebBuilder/blob/main/frontend/src/components/firmware-tool/ImuConfig.tsx#L67
Calculation: https://github.com/SlimeVR/SlimeVR-Firmware-WebBuilder/blob/main/backend/src/firmware/firmware.service.ts#L323
#define IMU_ROTATION ${firmware.buildConfig.imus[0].rotation} * PI / 180

in const.h in the firmware
#define DEG_0 0.f
#define DEG_90 -PI / 2
#define DEG_180 PI
#define DEG_270 PI / 2

that does not get the same result.

**Comment by ButterscotchV** [comment]
I asked on the Discord and got no response, but, to fix this, the rotation from the firmware builder just needs to be negative, right? The rotation defined in the firmware is in the negative direction and the equation from the firmware builder is equivalent but in the positive direction.

**Comment by unlogisch04** [comment]
Well i think the rotation is wrong, but this are the calculated values: 
![grafik](https://user-images.githubusercontent.com/98281608/207466422-88c0e57c-eeb3-4079-9f5b-1c35cbd7f64b.png)

Im too less familiar with quaternion and vector math to know what is correct.
So the offset would be not 0 but like 1 360° turn around in 0 offset and then backwards. Not sure if that works or if we would lose precision because of math.

**Comment by ButterscotchV** [comment]
For context, I looked at all the code for firmware and the web flasher, and I believe this change would fix it

```diff
-#define IMU_ROTATION ${firmware.buildConfig.imus[0].rotation} * PI / 180
+#define IMU_ROTATION ${-firmware.buildConfig.imus[0].rotation % 360} * PI / 180
```

**Comment by ButterscotchV** [comment]
Pushed changes to my site, feel free to test and see if it fixed it, in which case I'll make a PR
https://slimevr-firmware.bscotch.ca/
